TracAccountManager 0.5dev: Fix regression in r16330
{{{
TracError: Unable to instantiate component
<class 'acct_mgr.register.EmailVerificationModule'>
(join() takes exactly one argument (2 given))
}}}


git-svn-id: https://trac-hacks.org/svn/accountmanagerplugin/trunk@16653 7322e99d-02ea-0310-aa39-e9a107903beb